### ISSUE TITLE
Key is returned undefine value. Kindly help me to solve this issue.

### ISSUE THREAD

**Issue by sayandas1** [Tonel/multipart-upload-js-demo#1]

**Comment by Tonel** [comment]
Hi! 
What key are you referring to? Could you please provide more details?

**Comment by Haperious** [comment]
Hello, I am also receiving the same error. Well, I think we are getting the same error.
This is what it says, on my end.

(node:17756) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received 
undefined
    at new NodeError (internal/errors.js:322:7)
    at prepareSecretKey (internal/crypto/keys.js:322:11)
    at new Hmac (internal/crypto/hash.js:111:9)
    at Object.createHmac (crypto.js:148:10)
    at Object.hmac (C:\Users\Justinb\Desktop\Projects\multipart-upload-js-demo\node_modules\aws-sdk\lib\util.js:428:30)
    at Object.getSigningKey (C:\Users\Justinb\Desktop\Projects\multipart-upload-js-demo\node_modules\aws-sdk\lib\signers\v4_credentials.js:62:8)
    at V4.signature (C:\Users\Justinb\Desktop\Projects\multipart-upload-js-demo\node_modules\aws-sdk\lib\signers\v4.js:98:36)
    at V4.authorization (C:\Users\Justinb\Desktop\Projects\multipart-upload-js-demo\node_modules\aws-sdk\lib\signers\v4.js:93:36)
    at V4.addAuthorization (C:\Users\Justinb\Desktop\Projects\multipart-upload-js-demo\node_modules\aws-sdk\lib\signers\v4.js:35:12)
    at C:\Users\Justinb\Desktop\Projects\multipart-upload-js-demo\node_modules\aws-sdk\lib\event_listeners.js:264:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:17756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero 
exit code.

**Comment by Tonel** [comment]
I am not experiencing this issue, but this may be due to a wrong S3 configuration. I guess `key` is `undefined` because of an error happening in the S3 library. Is the endpoint configured correctly? Please consider giving a look at https://github.com/Tonel/multipart-upload-js-demo/issues/2
